2_3_change_model
thinknetica-django-lab-01/ivnnkt pull request #27
Opened 2021-01-25 08:38 UTC by ivnnkt

Closes #2

2021-01-25 20:06 UTC, mikhailborodin requested changes

2021-01-25 20:06 UTC, mikhailborodin commented on e_commerce/main/migrations/0005_auto_20210125_0015.py
> +    operations = [
в миграции нет операции по добавлению нового поля в таблицу БД, похоже на то что оно удалено

2021-01-25 21:25 UTC, ivnnkt commented on e_commerce/main/migrations/0006_auto_20210125_2344.py
> +        ('main', '0005_auto_20210125_0015'),
Поторопился и создал новую миграцию, когда понял что ошибся удалил ее, но не через гит, в итоге она вылезла и применилась. Что с ней можно сделать? удалить/оставить?

2021-01-26 18:12 UTC, mikhailborodin approved these changes

2021-01-26 18:13 UTC, merged