5_2_allauth
thinknetica-django-lab-01/ivnnkt pull request #45
Opened 2021-02-06 16:25 UTC by ivnnkt

Closes #34

2021-02-07 14:13 UTC, morgangt requested changes
Надо только удалить закомментированный код

2021-02-07 14:13 UTC, morgangt commented on e_commerce/main/templates/accounts/login.html
> +<!--{% endblock %}-->
эту часть кода надо удалить, так как она все равно отрабатывает, чтобы закомментировать такой код надо использовать тег `{# .. #}`
В целом в проекте не должно быть кода который ничего не делает, это запутывает и вносит дополнительную сложность при чтении.

2021-02-07 17:11 UTC, ivnnkt commented on e_commerce/main/templates/accounts/login.html
> +<!--{% endblock %}-->
я все подчистил в следующих модулях, в 5_3 или в 5_4, не помню, но точно подчистил, тут просто забыл про него, понимаю что лишний

2021-02-08 09:40 UTC, morgangt approved these changes

2021-02-08 09:40 UTC, morgangt commented on e_commerce/main/templates/accounts/login.html
> +<!--{% endblock %}-->
👍

2021-02-08 09:46 UTC, merged